# Generated by Django 2.1.1 on 2019-03-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('borrower_name', models.CharField(max_length=100)),
                ('borrow_time', models.DateField()),
            ],
        ),
    ]
