# Generated by Django 2.1.1 on 2019-03-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PinjamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('nomor_buku', models.CharField(max_length=50)),
                ('tanggal_pinjam', models.DateField()),
            ],
        ),
    ]
