# Generated by Django 2.1.1 on 2019-05-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shafiya_pinjam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinjammodel',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
