# Generated by Django 2.1.1 on 2019-03-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shafiya_pinjam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinjammodel',
            name='buku_dipinjam',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pinjammodel',
            name='nama_peminjam',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
