# Generated by Django 2.2a1 on 2019-04-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=250)),
                ('Pesan', models.CharField(max_length=5000)),
                ('Tanggal_Pesan', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
