# Generated by Django 2.2 on 2019-05-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_buku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='kuota',
            field=models.IntegerField(null=True),
        ),
    ]
