# Generated by Django 2.1.1 on 2019-03-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_buku', '0002_auto_20190321_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='cover',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
    ]
