# Generated by Django 2.2a1 on 2019-03-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('Nama', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('Nomor_Identitas', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=250)),
                ('Email', models.CharField(max_length=250)),
                ('Password', models.CharField(max_length=250)),
                ('Alamat_Rumah', models.CharField(max_length=500)),
            ],
        ),
    ]
