# Generated by Django 2.1.1 on 2019-03-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_anggota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Email',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
