# Generated by Django 2.1.1 on 2019-05-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_anggota', '0002_auto_20190427_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
    ]
