# Generated by Django 2.1.1 on 2019-05-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_anggota', '0003_auto_20190505_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
