# Generated by Django 2.1.1 on 2019-05-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_anggota', '0003_auto_20190502_1052'),
        ('form_anggota', '0004_auto_20190505_2028'),
    ]

    operations = [
    ]
