# Generated by Django 2.2 on 2019-05-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_anggota', '0005_merge_20190506_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
